# Generated by Django 5.0.6 on 2024-05-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, db_column='Type', max_length=50, null=True)),
                ('ssn', models.IntegerField(blank=True, db_column='SSN', null=True)),
                ('password', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(blank=True, db_column='Code', max_length=20, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, db_column='Gender', max_length=10, null=True)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
