# Generated by Django 5.0.6 on 2024-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_person_is_active_person_is_admin_person_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='last_login',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
