# Generated by Django 5.0.6 on 2024-05-21 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_person_date_joined_person_last_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Person',
            new_name='Account',
        ),
    ]
