# Generated by Django 5.0.6 on 2024-05-21 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(blank=True, db_column='Email', max_length=100, null=True, unique=True),
        ),
    ]
