# Generated by Django 5.0.6 on 2024-05-21 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_account_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse')], db_column='Type', default='user', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
