# Generated by Django 5.0.6 on 2024-05-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_account_type_alter_account_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='code',
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_column='Gender', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse')], db_column='Type', default='patient', max_length=20, null=True),
        ),
    ]
