# Generated by Django 5.0.6 on 2024-05-24 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_contact_no_alter_account_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='ssn',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
