# Generated by Django 5.0.6 on 2024-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_account_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('patient', 'Patient'), ('doctor', 'Doctor'), ('nurse', 'Nurse'), ('lab', 'Lab')], default='patient', max_length=20, null=True),
        ),
    ]
