# Generated by Django 5.0.6 on 2024-05-23 16:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_no', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedicalHis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcohol', models.BooleanField(default=False)),
                ('smoking', models.BooleanField(default=False)),
                ('high_blood_pressure', models.BooleanField(default=False)),
                ('diabetes', models.BooleanField(default=False)),
                ('high_colest', models.BooleanField(default=False)),
                ('patient_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Illness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('illness_name', models.CharField(max_length=100)),
                ('history_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalhis')),
            ],
            options={
                'unique_together': {('history_no', 'illness_name')},
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=100)),
                ('history_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalhis')),
            ],
            options={
                'unique_together': {('history_no', 'disease_name')},
            },
        ),
        migrations.CreateModel(
            name='CurrentMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('history_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalhis')),
            ],
            options={
                'unique_together': {('history_no', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(blank=True, choices=[('medication', 'Medication'), ('food', 'Food')], max_length=50, null=True)),
                ('history_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalhis')),
            ],
            options={
                'unique_together': {('history_no', 'name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='PrevSurgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_surgery_name', models.CharField(max_length=100)),
                ('history_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalhis')),
            ],
            options={
                'unique_together': {('history_no', 'prev_surgery_name')},
            },
        ),
        migrations.CreateModel(
            name='Vaccination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccination_name', models.CharField(max_length=100)),
                ('history_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicalhis')),
            ],
            options={
                'unique_together': {('vaccination_name', 'history_no')},
            },
        ),
    ]
