# Generated by Django 5.0.6 on 2024-05-24 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctoravailability_doctor'),
        ('patient', '0004_appointment_price_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('patient_no', 'availability_time')},
        ),
    ]
