# Generated by Django 5.0.6 on 2024-05-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnosislu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosisname', models.CharField(max_length=100, unique=True)),
                ('icd_code', models.IntegerField(default=0, unique=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('diagnositc_criteria', models.CharField(blank=True, max_length=500, null=True)),
                ('treatment_option', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicationlu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicationname', models.CharField(max_length=255, unique=True)),
                ('genericname', models.CharField(blank=True, max_length=255, null=True)),
                ('frequency', models.IntegerField(default=0)),
                ('strength', models.CharField(blank=True, max_length=50, null=True)),
                ('avdosage', models.IntegerField(blank=True, default=0, null=True)),
                ('routeofadministration', models.CharField(blank=True, max_length=100, null=True)),
                ('package', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('lactation', models.IntegerField(blank=True, null=True)),
                ('interaction', models.TextField(blank=True, null=True)),
                ('pregnancy', models.BooleanField(blank=True, null=True)),
                ('indication', models.TextField(blank=True, null=True)),
                ('children', models.BooleanField(blank=True, default=True, null=True)),
                ('effectondrive', models.TextField(blank=True, null=True)),
                ('overdose', models.TextField(blank=True, null=True)),
                ('sideeffects', models.TextField(blank=True, null=True)),
                ('contraindications', models.TextField(blank=True, null=True)),
                ('composition', models.TextField(blank=True, null=True)),
                ('storage', models.TextField(blank=True, null=True)),
                ('pharmaceuticalform', models.TextField(blank=True, null=True)),
                ('shelflife', models.CharField(blank=True, max_length=50, null=True)),
                ('warningandprecautions', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptomslu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptomsname', models.CharField(max_length=100, unique=True)),
                ('frequency', models.IntegerField(default=0)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('severity', models.CharField(blank=True, choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('severe', 'Severe')], max_length=50, null=True)),
            ],
        ),
    ]
