# Generated by Django 5.0.6 on 2024-05-25 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_note_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encounters',
            name='medication',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_name',
        ),
        migrations.RemoveField(
            model_name='test',
            name='test_type',
        ),
        migrations.AddField(
            model_name='encounters',
            name='tests',
            field=models.ManyToManyField(to='patient.test'),
        ),
        migrations.AddField(
            model_name='test',
            name='result',
            field=models.FileField(blank=True, null=True, upload_to='test_results/'),
        ),
        migrations.AddField(
            model_name='test',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Not Paid', 'Not Paid')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('frequency', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicationlu')),
            ],
        ),
        migrations.AddField(
            model_name='encounters',
            name='prescription',
            field=models.ManyToManyField(to='patient.prescription'),
        ),
        migrations.CreateModel(
            name='Testfiled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mesureunit', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('refrance_range_up', models.IntegerField(default=0)),
                ('refrance_range_down', models.IntegerField(default=0)),
            ],
            options={
                'unique_together': {('name', 'mesureunit')},
            },
        ),
        migrations.CreateModel(
            name='Testlu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testname', models.CharField(max_length=100, unique=True)),
                ('mesureunit', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.IntegerField(default=0)),
                ('testfileds', models.ManyToManyField(to='patient.testfiled')),
            ],
            options={
                'unique_together': {('testname', 'type')},
            },
        ),
        migrations.AddField(
            model_name='test',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.testlu'),
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
