# Generated by Django 5.0.6 on 2024-05-25 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_remove_encounters_medication_remove_test_test_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlu',
            name='mesureunit',
        ),
    ]
