# Generated by Django 5.0.6 on 2024-05-25 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_remove_testlu_mesureunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='testfiled',
            name='shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
