# Generated by Django 5.0.6 on 2024-05-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_remove_testfiled_shortname_testlu_shortname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testlu',
            name='shortname',
        ),
        migrations.AddField(
            model_name='testfiled',
            name='shortname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
