# Generated by Django 5.0.6 on 2024-05-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_alter_test_patient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounters',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, null=True, to='patient.diagnosislu'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='prescription',
            field=models.ManyToManyField(blank=True, null=True, to='patient.prescription'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='symptoms',
            field=models.ManyToManyField(blank=True, null=True, to='patient.symptomslu'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='tests',
            field=models.ManyToManyField(blank=True, null=True, to='patient.test'),
        ),
    ]
