# Generated by Django 5.0.6 on 2024-05-26 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_alter_encounters_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.appointment'),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=100),
        ),
    ]
