# Generated by Django 5.0.6 on 2024-05-26 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0017_test_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.IntegerField(default=0)),
                ('isupnormal', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('testfiled', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.testfiled')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='resultfileds',
            field=models.ManyToManyField(blank=True, null=True, to='patient.testresultfield'),
        ),
    ]
