# Generated by Django 5.0.6 on 2024-05-26 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_test_result_test_result_notes_test_resultfileds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='resultfileds',
        ),
        migrations.AddField(
            model_name='testresultfield',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.test'),
        ),
    ]
