# Generated by Django 5.0.6 on 2024-05-27 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_alter_test_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='encounters',
            name='diagnosis',
            field=models.ManyToManyField(blank=True, to='patient.diagnosislu'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='prescription',
            field=models.ManyToManyField(blank=True, to='patient.prescription'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='symptoms',
            field=models.ManyToManyField(blank=True, to='patient.symptomslu'),
        ),
        migrations.AlterField(
            model_name='encounters',
            name='tests',
            field=models.ManyToManyField(blank=True, to='patient.test'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
