# Generated by Django 5.0.6 on 2024-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0025_alter_encounters_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='image',
            field=models.ImageField(default='images/faces/default-profile.svg', upload_to='patient_images/'),
        ),
    ]
