# Generated by Django 5.0.6 on 2024-05-24 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
        ('patient', '0007_encounters'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.patient'),
        ),
    ]
