# Generated by Django 5.0.6 on 2024-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_initialassessment_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='initialassessment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
