# Generated by Django 5.0.6 on 2024-05-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='medical_id',
        ),
        migrations.AlterField(
            model_name='department',
            name='fees',
            field=models.IntegerField(default=0),
        ),
    ]
