# Generated by Django 5.0.6 on 2024-05-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0005_alter_doctoravailability_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailability',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
